"""
Django settings for bip_ead project.

Generated by 'django-admin startproject' using Django 4.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'bip_ead2', 'templates', 'static'),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8f8+(1*q@z8d1f7#0rtoyi1yodzng!d$oc$5!=f_wwf9a2b^1+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bip_ead2'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE.insert(
    MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware') + 1,
    'bip_ead2.middleware.NoRememberMiddleware'
)
ROOT_URLCONF = 'bip_ead.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bip_ead.wsgi.application'
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 dias
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
MONGO_DB_URI = "mongodb+srv://pedrovilanova34_db_user:Peter123@cluster0.wl5xgth.mongodb.net/"
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'Dados',
        'ENFORCE_SCHEMA': False,  # Adicione esta linha
        'CLIENT': {
            'host': MONGO_DB_URI,
        }
    }
}
#MONGOENGINE_USER_DOCUMENT = 'mongoengine.django.auth.User
AUTHENTICATION_BACKENDS = [
    'bip_ead2.backends.MongoDBBackend',  # Caminho correto para o seu backend
    'django.contrib.auth.backends.ModelBackend'
]


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ALLOWED_HOSTS = ['*']
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # Porta para TLS
EMAIL_USE_TLS = True  # Usar TLS
EMAIL_USE_SSL = False  # Não usar SSL (conflita com TLS)
EMAIL_HOST_USER = 'bipead@gmail.com'
EMAIL_HOST_PASSWORD = 'juwy etsh vusg tirt'  # App Password gerado
DEFAULT_FROM_EMAIL = 'bipead@gmail.com'
SERVER_EMAIL = 'bipead@gmail.com'
CSRF_USE_SESSIONS = False  # Padrão recomendado
CSRF_COOKIE_HTTPONLY = False  # Necessário para acesso via JS
CSRF_COOKIE_SECURE = False  # True se usando HTTPS em produção
CSRF_COOKIE_SAMESITE = 'Lax'  # Ou 'Strict' para mais segurança
